### ISSUE TITLE
Adding dark and light theme using react context

### ISSUE THREAD

**Issue by n1rjal** [enjeck/gfolio#4]
I have raised this issue to reserve Dark and Light theme contribution to myself. For some reason, if I can't contribute, I will open this issue for contribution to anyone. But for now, I request @enjeck to put this contribution for myself.

**Comment by enjeck** [comment]
@n1rjal Thank you for volunteering to do this. 

By the way, this feature should be activated in "Settings", located at the footer. I had started creating it in the footer, but commented it since the dark mode feature wasn't available. See here: https://github.com/enjeck/gfolio/blob/main/src/pages/home.js#L101-L111
Here is the styling for the settings dropdown: https://github.com/enjeck/gfolio/blob/main/src/styles.css#L118-L160. It might need some more work.
